In [1]:
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

### Problem 1

In [16]:
x = np.arange(1, 11)
print(f"position 3: {x[2]}, last position: {x[-1]}")

position 3: 3, last position: 10


### Problem 2

In [4]:
x = np.arange(2, 49, 2)
total = np.sum(x)
avg = np.average(x)
print(f'total: {total}, average: {avg}')

total: 600, average: 25.0


### Problem 3

In [5]:
x = np.arange(3, 66, 2)
y = x[1::2]
y

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65])

### Problem 4

In [6]:
t = np.arange(0, 101)
t_squared = np.pow(t, 2)
t_squared

array([    0,     1,     4,     9,    16,    25,    36,    49,    64,
          81,   100,   121,   144,   169,   196,   225,   256,   289,
         324,   361,   400,   441,   484,   529,   576,   625,   676,
         729,   784,   841,   900,   961,  1024,  1089,  1156,  1225,
        1296,  1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,
        2025,  2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,
        2916,  3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,
        3969,  4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,
        5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,
        6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
        8100,  8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,
        9801, 10000])

### Problem 5

In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
summation = np.add(a, b)
multi = np.multiply(a, b)
summation, multi

(array([6, 6, 6, 6, 6]), array([5, 8, 9, 8, 5]))

### Problem 6

In [8]:
x = np.array([0, 2, 8, 18, 32])
t = np.array([0, 1, 2, 3, 4])

t1 = t[0:-1]
print(f't1: {t1}')

t2 = t[1:]
print(f't2: {t2}')

x1 = x[0:-1]
print(f'x1: {x1}')

x2 = x[1:]
print(f'x2: {x2}')

c = (x2-x1) / (t2-t1)
print(f'avg v (m/s): {c}')

t1: [0 1 2 3]
t2: [1 2 3 4]
x1: [ 0  2  8 18]
x2: [ 2  8 18 32]
avg v (m/s): [ 2.  6. 10. 14.]


### Problem 7

In [9]:
m = 1.5
v = np.arange(0, 21, 2)
v_squared = np.pow(v, 2)
kinetic = np.multiply(v_squared, 1/2*m)
print(f'kinetic energy: {kinetic}')

kinetic energy: [  0.   3.  12.  27.  48.  75. 108. 147. 192. 243. 300.]


### Problem 8

In [18]:
T = np.array([22.1, 22.8, 23.6, 24.5, 25.3, 26.0, 26.5, 26.9, 27.1, 27.0])
t_max = np.argmax(T)+1
maxT = T[t_max-1]

print(f'Highest temperature {maxT} at t = {t_max}')

Highest temperature 27.1 at t = 9


### Problem 9

In [11]:
V = np.array([2, 3, 5, 7, 10, 12])
R = np.array([1, 2, 2.5, 3, 4, 5])

I = np.divide(V, R)
P = np.multiply(I, V)

print(f'Current: {I}')
print(f'Power: {P}')

Current: [2.         1.5        2.         2.33333333 2.5        2.4       ]
Power: [ 4.          4.5        10.         16.33333333 25.         28.8       ]


### Problem 10

In [12]:
a = 2
u = 1

t = np.arange(0, 5.1, 0.1)
print(f'time (s): {t}')

v = u + (a*t)
print(f'v (m/s): {v}')

x = (u*t) + (1/2)*a*np.pow(t, 2)
print(f'x (m): {x}')

time (s): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5. ]
v (m/s): [ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11. ]
x (m): [ 0.    0.11  0.24  0.39  0.56  0.75  0.96  1.19  1.44  1.71  2.    2.31
  2.64  2.99  3.36  3.75  4.16  4.59  5.04  5.51  6.    6.51  7.04  7.59
  8.16  8.75  9.36  9.99 10.64 11.31 12.   12.71 13.44 14.19 14.96 15.75
 16.56 17.39 18.24 19.11 20.   20.91 21.84 22.79 23.76 24.75 25.76 26.79
 27.84 28.91 30.  ]


### Problem 11

In [13]:
x = np.array([0.98, 1.02, 1.00, 1.01, 0.99])
avg = np.average(x)
std = np.std(x)
print(f'average: {avg}, standard deviation: {std}')

average: 1.0, standard deviation: 0.014142135623730963


### Problem 12

In [14]:
# special relativity
v_c = np.arange(0, 1.05, 0.05)
m = 1
print('m0:', m, 'kg')
M = m/np.sqrt(1- np.pow(v_c, 2))
M_m = np.divide(M, m)
print('v/c:', v_c)
print('m/m0:', M_m)
print(f'm/m0 ≈ 1.5 when v/c ≈ 3/4')
print('------------------------------------')
print('Discussion: As the ratio of speed to the speed of light approaches 1, mass increases to infinity, or in other words, as we approach the speed of light, mass increases.')

m0: 1 kg
v/c: [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]
m/m0: [1.         1.00125235 1.00503782 1.01144347 1.02062073 1.03279556
 1.04828484 1.06752103 1.09108945 1.11978502 1.15470054 1.19736868
 1.25       1.31590339 1.40028008 1.51185789 1.66666667 1.89831599
 2.29415734 3.20256308        inf]
m/m0 ≈ 1.5 when v/c ≈ 3/4
------------------------------------
Discussion: As the ratio of speed to the speed of light approaches 1, mass increases to infinity, or in other words, as we approach the speed of light, mass increases.
